### ISSUE TITLE
Reorganize the `certificates` key

### ISSUE THREAD

**Issue by jvoisin** [AssoEchap/stalkerware-indicators#93]
Have something like this instead:

```yaml
certificates:
  fingerprint: []
  cname: []
  org: []
  cname_re: []
  org-re: []
```
